root = window || @

class root.EmojifyChooser extends Backbone.View
  tagName: 'ul'
  className: 'emojify-chooser'

  emoticons: [
    ['bowtie', '蝴蝶结'],
    ['smile', '微笑'],
    ['laughing', '大笑'],
    ['blush', '脸红'],
    ['smiley', '笑脸'],
    ['relaxed', '放松'],
    ['smirk', '傻笑'],
    ['heart_eyes', '爱慕'],
    ['kissing_heart', '飞吻'],
    ['kissing_closed_eyes', '亲亲'],
    ['flushed', '可爱'],
    ['relieved', '释然'],
    # ['satisfied', '满意'],
    ['grin', '咧嘴'],
    ['wink', '眨眼'],
    ['stuck_out_tongue_winking_eye', '媚眼'],
    ['stuck_out_tongue_closed_eyes', '卖萌'],
    ['grinning', '奸笑'],
    ['kissing', '亲吻'],
    ['kissing_smiling_eyes', '啵个'],
    ['stuck_out_tongue', '吐舌'],
    ['sleeping', '睡觉'],
    ['worried', '担忧'],
    ['frowning', '皱眉'],
    ['anguished', '苦涩'],
    ['open_mouth', '张嘴'],
    ['grimacing', '鬼脸'],
    ['confused', '迷茫'],
    ['hushed', '安静'],
    ['expressionless', '冷酷'],
    ['unamused', '伤心'],
    ['sweat_smile', '汗笑'],
    ['sweat', '汗颜'],
    ['weary', '厌倦'],
    ['pensive', '哀思'],
    ['disappointed', '失望'],
    ['confounded', '困惑'],
    ['fearful', '可怕'],
    ['cold_sweat', '冷汗'],
    ['persevere', '坚持'],
    ['cry', '落泪'],
    ['sob', '哭泣'],
    ['joy', '愉快'],
    ['scream', '惊恐'],
    ['astonished', '惊讶'],
    ['neckbeard', '大叔'],
    ['tired_face', '疲惫'],
    ['angry', '生气'],
    ['rage', '怒火'],
    ['triumph', '凯旋'],
    ['sleepy', '困乏'],
    ['yum', '胜利'],
    ['mask', '口罩'],
    ['sunglasses', '墨镜'],
    ['dizzy_face', '晕了'],
    ['imp', '恶魔'],
    ['smiling_imp', '微笑恶魔'],
    ['neutral_face', '抿嘴'],
    ['no_mouth', '闭嘴'],
    ['innocent', '天使 '],
    ['alien', '外星人'],
    ['yellow_heart', '胆小害怕'],
    ['blue_heart', '忧郁心情'],
    ['purple_heart', '紫色勋章'],
    ['heart', '爱心'],
    ['green_heart', '年轻的心'],
    ['broken_heart', '心碎'],
    ['heartbeat', '心跳'],
    ['heartpulse', '心脉'],
    ['two_hearts', '两心相对'],
    ['revolving_hearts', '两心相伴'],
  ]
  extra: [
    ['cupid', '一见钟情'],
    ['sparkling_heart', 'emojify sparkling_heart'],
    ['sparkles', 'emojify sparkles'],
    ['star', 'emojify star'],
    ['star2', 'emojify star2'],
    ['dizzy', 'emojify dizzy'],
    ['boom', 'emojify boom'],
    ['collision', 'emojify collision'],
    ['anger', 'emojify anger'],
    ['exclamation', 'emojify exclamation'],
    ['question', 'emojify question'],
    ['grey_exclamation', 'emojify grey_exclamation'],
    ['grey_question', 'emojify grey_question'],
    ['zzz', 'emojify zzz'],
    ['dash', 'emojify dash'],
    ['sweat_drops', 'emojify sweat_drops'],
    ['notes', 'emojify notes'],
    ['musical_note', 'emojify musical_note'],
    ['fire', 'emojify fire'],
    ['hankey', 'emojify hankey'],
    ['poop', 'emojify poop'],
    ['shit', 'emojify shit'],
    ['+1', 'emojify thumbsup'],
    ['-1', 'emojify thumbsdown'],
    ['ok_hand', 'emojify ok_hand'],
    ['punch', 'emojify punch'],
    ['facepunch', 'emojify facepunch'],
    ['fist', 'emojify fist'],
    ['v', 'emojify v'],
    ['wave', 'emojify wave'],
    ['hand', 'emojify hand'],
    ['open_hands', 'emojify open_hands'],
    ['point_up', 'emojify point_up'],
    ['point_down', 'emojify point_down'],
    ['point_left', 'emojify point_left'],
    ['point_right', 'emojify point_right'],
    ['raised_hands', 'emojify raised_hands'],
    ['pray', 'emojify pray'],
    ['point_up_2', 'emojify point_up_2'],
    ['clap', 'emojify clap'],
    ['muscle', 'emojify muscle'],
    ['metal', 'emojify metal'],
    ['walking', 'emojify walking'],
    ['runner', 'emojify runner'],
    ['running', 'emojify running'],
    ['couple', 'emojify couple'],
    ['family', 'emojify family'],
    ['two_men_holding_hands', 'emojify two_men_holding_hands'],
    ['two_women_holding_hands', 'emojify two_women_holding_hands'],
    ['dancer', 'emojify dancer'],
    ['dancers', 'emojify dancers'],
    ['ok_woman', 'emojify ok_woman'],
    ['no_good', 'emojify no_good'],
    ['information_desk_person', 'emojify information_desk_person'],
    ['raised_hand', 'emojify raised_hand'],
    ['bride_with_veil', 'emojify bride_with_veil'],
    ['person_with_pouting_face', 'emojify person_with_pouting_face'],
    ['person_frowning', 'emojify person_frowning'],
    ['bow', 'emojify bow'],
    ['couplekiss', 'emojify couplekiss'],
    ['couple_with_heart', 'emojify couple_with_heart'],
    ['massage', 'emojify massage'],
    ['haircut', 'emojify haircut'],
    ['nail_care', 'emojify nail_care'],
    ['boy', 'emojify boy'],
    ['girl', 'emojify girl'],
    ['woman', 'emojify woman'],
    ['man', 'emojify man'],
    ['baby', 'emojify baby'],
    ['older_woman', 'emojify older_woman'],
    ['older_man', 'emojify older_man'],
    ['person_with_blond_hair', 'emojify person_with_blond_hair'],
    ['man_with_gua_pi_mao', 'emojify man_with_gua_pi_mao'],
    ['man_with_turban', 'emojify man_with_turban'],
    ['construction_worker', 'emojify construction_worker'],
    ['cop', 'emojify cop'],
    ['angel', 'emojify angel'],
    ['princess', 'emojify princess'],
    ['smiley_cat', 'emojify smiley_cat'],
    ['smile_cat', 'emojify smile_cat'],
    ['heart_eyes_cat', 'emojify heart_eyes_cat'],
    ['kissing_cat', 'emojify kissing_cat'],
    ['smirk_cat', 'emojify smirk_cat'],
    ['scream_cat', 'emojify scream_cat'],
    ['crying_cat_face', 'emojify crying_cat_face'],
    ['joy_cat', 'emojify joy_cat'],
    ['pouting_cat', 'emojify pouting_cat'],
    ['japanese_ogre', 'emojify japanese_ogre'],
    ['japanese_goblin', 'emojify japanese_goblin'],
    ['see_no_evil', 'emojify see_no_evil'],
    ['hear_no_evil', 'emojify hear_no_evil'],
    ['speak_no_evil', 'emojify speak_no_evil'],
    ['guardsman', 'emojify guardsman'],
    ['skull', 'emojify skull'],
    ['feet', 'emojify feet'],
    ['lips', 'emojify lips'],
    ['kiss', 'emojify kiss'],
    ['droplet', 'emojify droplet'],
    ['ear', 'emojify ear'],
    ['eyes', 'emojify eyes'],
    ['nose', 'emojify nose'],
    ['tongue', 'emojify tongue'],
    ['love_letter', 'emojify love_letter'],
    ['bust_in_silhouette', 'emojify bust_in_silhouette'],
    ['busts_in_silhouette', 'emojify busts_in_silhouette'],
    ['speech_balloon', 'emojify speech_balloon'],
    ['thought_balloon', 'emojify thought_balloon'],
    ['feelsgood', 'emojify feelsgood'],
    ['finnadie', 'emojify finnadie'],
    ['goberserk', 'emojify goberserk'],
    ['godmode', 'emojify godmode'],
    ['hurtrealbad', 'emojify hurtrealbad'],
    ['rage1', 'emojify rage1'],
    ['rage2', 'emojify rage2'],
    ['rage3', 'emojify rage3'],
    ['rage4', 'emojify rage4'],
    ['suspect', 'emojify suspect'],
    ['trollface', 'emojify trollface']
  ]

  @getInstance = (options) ->
    EmojifyChooser.instance ||= new EmojifyChooser(options)

  initialize: () ->
    html = ''
    _.each this.emoticons, (item) =>
      html += '<li><img src="/assets/emojis/' + item[0] + '.png" class="emoji" data-name="' + item[0] + '" title="' + item[1] + '" alt="' + item[1] + '" /></li>'
    $(@el).append(html)

