bank:
    -
        中国银行:
            name: 中国银行
            code: BOC
    -
        工商银行:
            name: 工商银行
            code: ICBC
    -
        建设银行:
            name: 建设银行
            code: CCB
    -
        农业银行:
            name: 农业银行
            code: ABC
    -
        招商银行:
            name: 招商银行
            code: CMB
    -
        民生银行:
            name: 中国民生银行
            code: CMBC
    -
        交通银行:
            name: 交通银行
            code: BCOM
    -
        兴业银行:
            name: 兴业银行
            code: CIB

    -
        中信银行:
            name: 中信银行
            code: CITIC
