remote: https://www.99bill.com/gateway/recvMerchantInfoAction.htm
environment: development
rsa:
  path: public/99bill-rsa.pem
  password: asdfasdf

params:
  merchant_acct_id: 1002300593701
  version: v2.0
  language: "1"
  sign_type: "4"
