require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe People::TransactionsController do

  # This should return the minimal set of attributes required to create a valid
  # People::Transaction. As you add validations to People::Transaction, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # People::TransactionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all people_transactions as @people_transactions" do
      transaction = People::Transaction.create! valid_attributes
      get :index, {}, valid_session
      assigns(:people_transactions).should eq([transaction])
    end
  end

  describe "GET show" do
    it "assigns the requested people_transaction as @people_transaction" do
      transaction = People::Transaction.create! valid_attributes
      get :show, {:id => transaction.to_param}, valid_session
      assigns(:people_transaction).should eq(transaction)
    end
  end

  describe "GET new" do
    it "assigns a new people_transaction as @people_transaction" do
      get :new, {}, valid_session
      assigns(:people_transaction).should be_a_new(People::Transaction)
    end
  end

  describe "GET edit" do
    it "assigns the requested people_transaction as @people_transaction" do
      transaction = People::Transaction.create! valid_attributes
      get :edit, {:id => transaction.to_param}, valid_session
      assigns(:people_transaction).should eq(transaction)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new People::Transaction" do
        expect {
          post :create, {:people_transaction => valid_attributes}, valid_session
        }.to change(People::Transaction, :count).by(1)
      end

      it "assigns a newly created people_transaction as @people_transaction" do
        post :create, {:people_transaction => valid_attributes}, valid_session
        assigns(:people_transaction).should be_a(People::Transaction)
        assigns(:people_transaction).should be_persisted
      end

      it "redirects to the created people_transaction" do
        post :create, {:people_transaction => valid_attributes}, valid_session
        response.should redirect_to(People::Transaction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved people_transaction as @people_transaction" do
        # Trigger the behavior that occurs when invalid params are submitted
        People::Transaction.any_instance.stub(:save).and_return(false)
        post :create, {:people_transaction => {  }}, valid_session
        assigns(:people_transaction).should be_a_new(People::Transaction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        People::Transaction.any_instance.stub(:save).and_return(false)
        post :create, {:people_transaction => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested people_transaction" do
        transaction = People::Transaction.create! valid_attributes
        # Assuming there are no other people_transactions in the database, this
        # specifies that the People::Transaction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        People::Transaction.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => transaction.to_param, :people_transaction => { "these" => "params" }}, valid_session
      end

      it "assigns the requested people_transaction as @people_transaction" do
        transaction = People::Transaction.create! valid_attributes
        put :update, {:id => transaction.to_param, :people_transaction => valid_attributes}, valid_session
        assigns(:people_transaction).should eq(transaction)
      end

      it "redirects to the people_transaction" do
        transaction = People::Transaction.create! valid_attributes
        put :update, {:id => transaction.to_param, :people_transaction => valid_attributes}, valid_session
        response.should redirect_to(transaction)
      end
    end

    describe "with invalid params" do
      it "assigns the people_transaction as @people_transaction" do
        transaction = People::Transaction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        People::Transaction.any_instance.stub(:save).and_return(false)
        put :update, {:id => transaction.to_param, :people_transaction => {  }}, valid_session
        assigns(:people_transaction).should eq(transaction)
      end

      it "re-renders the 'edit' template" do
        transaction = People::Transaction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        People::Transaction.any_instance.stub(:save).and_return(false)
        put :update, {:id => transaction.to_param, :people_transaction => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested people_transaction" do
      transaction = People::Transaction.create! valid_attributes
      expect {
        delete :destroy, {:id => transaction.to_param}, valid_session
      }.to change(People::Transaction, :count).by(-1)
    end

    it "redirects to the people_transactions list" do
      transaction = People::Transaction.create! valid_attributes
      delete :destroy, {:id => transaction.to_param}, valid_session
      response.should redirect_to(people_transactions_url)
    end
  end

end
